# Generated by Django 4.2.6 on 2023-10-30 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teste', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='cpf',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('CS', 'Casado'), ('VD', 'Viuvo'), ('SE', 'Separado'), ('UN', 'União Estável'), ('OU', 'Outros'), ('', 'Nenhum')], default='', max_length=2),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='rg',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='idade',
            field=models.IntegerField(blank=True),
        ),
    ]
