# Generated by Django 4.2.6 on 2023-10-30 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teste', '0003_pessoa_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='genero',
            field=models.CharField(blank=True, choices=[('FE', 'Feminino'), ('MA', 'Masculino'), ('AG', 'Agenero'), ('FL', 'Genero Fluido'), ('NB', 'Nao Binario'), ('OU', 'Outro'), ('', 'Nenhum')], default='', max_length=2),
        ),
    ]
