# Generated by Django 4.2.6 on 2023-10-30 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teste', '0004_alter_pessoa_genero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='rg',
        ),
    ]
