# Generated by Django 4.2.7 on 2023-11-01 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teste', '0005_remove_pessoa_rg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True)),
                ('state', models.CharField(max_length=2, null=True)),
                ('country', models.CharField(max_length=50, null=True)),
                ('zipCode', models.IntegerField(null=True)),
                ('street', models.CharField(max_length=50, null=True)),
                ('dscrptn', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='estado_civil',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='idade',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='nome',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='age',
            field=models.IntegerField(blank='', null=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='gender',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='lastName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='occupation',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='cidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teste.cidade'),
        ),
    ]
