# Generated by Django 4.2.7 on 2023-11-01 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teste', '0006_cidade_remove_pessoa_cpf_remove_pessoa_date_added_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cidade',
            name='street',
        ),
        migrations.RemoveField(
            model_name='cidade',
            name='zipCode',
        ),
        migrations.AlterField(
            model_name='cidade',
            name='dscrptn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
